# Site settings
title: "指明臺"
description: '个人信息& 业务介绍'
cover: images/forest.jpg
baseurl: ''
google_analytics: ''
disqus_shortname: 'Saar'

author:
  name: '指明臺文化咨詢'
  pronouns: 宇守正
  email: UCGKY00@outlook.com
  github:  
  linkedin:  
  stackoverflow:  
  hackerrank: 
  leetcode: 

collections_dir: my_collections
collections:
  dtsd:
    output: true
    permalink: /:collection/:path
    title: "Digital technology and sustainable development"
    show: true
  ro:
    output: true
    permalink: /:collection/:path
    title: "Research obstacles for climate change policy"
    show: true
  qa:
    output: true
    permalink: /:collection/:path
    title: "Quantitative Analysis of Australian mining coal"
    show: true
  cbdc:
    output: true
    permalink: /:collection/:path
    title: "China's social credit system and CBDC"
    show: true
  speech-recognition:
    output: false
    permalink: /:collection/:path
    title: "Speech Recognition"
    show: false
  speech-synthesis:
    output: false
    permalink: /:collection/:path
    title: "Speech Synthesis"
    show: false
  speech-translation:
    output: false
    permalink: /:collection/:path
    title: "Speech Translation"
    show: false
  word-embedding:
    output: false
    permalink: /:collection/:path
    title: "Word Embedding"
    show: false
  misc:
    output: true
    permalink: /:collection/:path
    title: "Misc."
    show: false

defaults:
  -
    scope:
      path: "my_collections/*" # all files inside my_collections
    values:
      layout: "post" #post.html

# Build settings
destination: _site
# paginate: 10
# permalink: /:collection
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  mathjax: true  #use mathjax to process math equations
  input: GFM # use Github Flavored Markdown
  hard_wrap: false # do not replace newlines by <br>

# plugins:
#   - jekyll-paginate
#   - jekyll-spaceship

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
