# Site settings
title: "Saar's Profile"
description: 'Research experience, a short five-minute presentation'
cover: images/forest.jpg
baseurl: ''
google_analytics: 'G-D53BTZQ94B'
disqus_shortname: 'anwarvic'

author:
  name: 'Mohamed Anwar'
  pronouns: "(he/him/his)"
  email: mohamedanwarvic@gmail.com
  github:  anwarvic
  linkedin:  anwarvic
  stackoverflow:  5612363/anwarvic
  hackerrank: anwarvic
  leetcode: anwarvic

collections_dir: my_collections
collections:
  language-modeling:
    output: true
    permalink: /:collection/:path
    title: "Industry 4.0; Digital technology and sustainable development in Australia"
    show: true
  machine-translation:
    output: true
    permalink: /:collection/:path
    title: "Research obstacles and possible solutions for climate change policy under the European green deal"
    show: true
  multilingual-nmt:
    output: true
    permalink: /:collection/:path
    title: "Quantitative Analysis of Australian mining coal industry"
    show: true
  cross-lingual-lm:
    output: true
    permalink: /:collection/:path
    title: "China's social credit system combined with the central bank's digital currency: The Practice of Control"
    show: true
  speech-recognition:
    output: true
    permalink: /:collection/:path
    title: "Speech Recognition"
    show: true
  speech-synthesis:
    output: true
    permalink: /:collection/:path
    title: "Speech Synthesis"
    show: true
  speech-translation:
    output: true
    permalink: /:collection/:path
    title: "Speech Translation"
    show: true
  word-embedding:
    output: true
    permalink: /:collection/:path
    title: "Word Embedding"
    show: false
  misc:
    output: true
    permalink: /:collection/:path
    title: "Misc."
    show: false

defaults:
  -
    scope:
      path: "my_collections/*" # all files inside my_collections
    values:
      layout: "post" #post.html

# Build settings
destination: _site
# paginate: 10
# permalink: /:collection
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  mathjax: true  #use mathjax to process math equations
  input: GFM # use Github Flavored Markdown
  hard_wrap: false # do not replace newlines by <br>

# plugins:
#   - jekyll-paginate
#   - jekyll-spaceship

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
